import { app, BrowserWindow, ipcMain } from 'electron';
import { createWindow } from './main';
import { createTray, destroyTray } from './tray';
import { createAutoUpdaterService } from './services/auto-updater';
import './ipc'; // Initialize IPC handlers

// Import necessary services and managers
import { analyticsService } from './services/analytics/analytics-service';
import { onboardingService } from './services/onboarding/onboarding-service';
import { licenseService } from './services/licensing/license-service';
import { WidgetManager, initializeWidgetManagement } from './widget-manager';
import { SettingsManager, initializeSettingsManagement } from './settings-manager';
import { initializeIpcHandlers } from './ipc';
import { registerIpcHandlers } from './services/ipc-handlers';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const WIDGET_WINDOW_WEBPACK_ENTRY: string;
declare const WIDGET_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const ONBOARDING_WINDOW_WEBPACK_ENTRY: string;
declare const ONBOARDING_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Define necessary state variables here
let widgetManager: WidgetManager | null = null;
let settingsManager: SettingsManager | null = null;
let ipcHandlersInitialized = false;
let mainWindow: BrowserWindow | null = null;

// Move app lifecycle listeners here
app.whenReady().then(async () => {
  try {
    // Initialize services first
    analyticsService.trackEvent('app_started', {
      version: app.getVersion(),
      platform: process.platform,
    });

    // Initialize managers
    widgetManager = await initializeWidgetManagement();
    settingsManager = await initializeSettingsManagement();

    // Initialize IPC handlers after managers are ready
    if (!ipcHandlersInitialized) {
      initializeIpcHandlers();
      registerIpcHandlers(); // Register service handlers
      ipcHandlersInitialized = true;
    }

    // Create main window
    mainWindow = createWindow();

    // Check and show onboarding if needed
    // Now uses constants defined within this scope
    await onboardingService.checkAndShowOnboarding();

    // Check license status
    const licenseInfo = await licenseService.getLicenseInfo();
    if (!licenseInfo.isValid) {
      analyticsService.trackEvent('license_check_failed', {
        type: licenseInfo.type,
        days_remaining: licenseInfo.daysRemaining,
      });
    }
  } catch (error) {
    console.error('Failed to initialize application:', error);
    analyticsService.captureError(error as Error, {
      context: 'app_initialization',
    });
    app.quit();
  }
});

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindow = createWindow();
  }
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('before-quit', () => {
  destroyTray(); // Ensure tray is destroyed
  if (widgetManager) {
    widgetManager.dispose();
    widgetManager = null;
  }
  if (settingsManager) {
    settingsManager.dispose();
    settingsManager = null;
  }
  analyticsService.trackEvent('app_quit', {
    version: app.getVersion(),
    uptime: process.uptime(),
  });
});

// Auto-updater IPC handlers (moved here for clarity)
app.whenReady().then(() => {
  if (mainWindow) {
    const autoUpdater = createAutoUpdaterService(mainWindow);
    ipcMain.handle('check-for-updates', () => autoUpdater?.checkForUpdates());
    ipcMain.handle('download-update', () => autoUpdater?.downloadUpdate());
    ipcMain.handle('quit-and-install', () => autoUpdater?.quitAndInstall());
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
