import { app, BrowserWindow, ipcMain } from 'electron';
import { createWindow } from './main';
import { createTray, destroyTray } from './tray';
import { createAutoUpdaterService } from './services/auto-updater';
import './ipc'; // Initialize IPC handlers

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let autoUpdater: ReturnType<typeof createAutoUpdaterService> | null = null;

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  mainWindow = createWindow();
  createTray(mainWindow);
  
  // Initialize auto-updater
  if (mainWindow) {
    autoUpdater = createAutoUpdaterService(mainWindow);
  }

  // Set up IPC handlers for auto-updater
  ipcMain.handle('check-for-updates', () => {
    autoUpdater?.checkForUpdates();
  });

  ipcMain.handle('download-update', () => {
    autoUpdater?.downloadUpdate();
  });

  ipcMain.handle('quit-and-install', () => {
    autoUpdater?.quitAndInstall();
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindow = createWindow();
    if (mainWindow) {
      autoUpdater = createAutoUpdaterService(mainWindow);
    }
  }
});

app.on('before-quit', () => {
  destroyTray();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
